# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    docker build -t my-container-image-name .
  displayName: 'build Docker image'

- task: SnykSecurityScan@0
  inputs:
    serviceConnectionEndpoint: 'Snyk Pipelines Example Connection'
    testType: 'container'
    dockerImageName: 'my-container-image-name'
    dockerfilePath: 'Dockerfile'
    monitorOnBuild: true
    failOnIssues: true